#!/usr/bin/env python3
"""
Agenticana Post-Task Auto-Commit Hook (P22 v7.2)
=================================================
Runs AFTER a dashboard task completes.
- Updates ROADMAP.md / README.md with task results
- Stages all changed files
- Commits with a timestamped message
- Pushes to GitHub
"""
import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parent.parent
ROADMAP  = BASE_DIR / "ROADMAP.md"
INTEL_PATH = BASE_DIR / ".Agentica" / "competitor_intel.json"
LOG_PATH   = BASE_DIR / ".Agentica" / "logs" / "dashboard_action.log"


def log(msg: str):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def git(args: list, cwd=BASE_DIR) -> str:
    result = subprocess.run(
        ["git"] + args, capture_output=True, text=True, cwd=str(cwd)
    )
    return (result.stdout + result.stderr).strip()


def changed_files() -> list[str]:
    out = git(["status", "--porcelain"])
    return [line[3:].strip() for line in out.splitlines() if line.strip()]


def update_roadmap_intel(intel: list):
    """Append competitor intel summary to ROADMAP if not already present."""
    if not ROADMAP.exists() or not intel:
        return
    content = ROADMAP.read_text(encoding="utf-8")
    section_header = "\n## 🕵️ Live Competitor Intel (Auto-Updated)\n"
    # Remove old section
    if section_header in content:
        content = content[:content.index(section_header)]

    rows = "\n".join(
        f"| `{r.get('repo','?')}` | {', '.join(r.get('trending_requests', [])[:2])} | {r.get('scanned_at','')[:10]} |"
        for r in intel[:11]
    )
    table = (
        f"{section_header}"
        f"> Auto-generated by Sovereign Intel Swarm on {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
        f"| Repo | Top Feature Gaps | Scanned |\n"
        f"|------|-----------------|----------|\n"
        f"{rows}\n\n"
        f"*Secretary Bird: always watching. 🦅*\n"
    )
    ROADMAP.write_text(content + table, encoding="utf-8")
    log("[+] ROADMAP.md updated with competitor intel table")


def commit_and_push(task: str):
    files = changed_files()
    if not files:
        log("[!] No changed files to commit")
        return

    log(f"[*] Staging {len(files)} changed file(s): {files}")
    git(["add", "-A"])

    ts = datetime.now().strftime("%Y-%m-%d %H:%M")
    msg = {
        "intel": f"🔍 Auto-commit: Competitor Intel Update [{ts}]\n\nSovereign Intel Swarm scanned 11 competitor repos.\nUpdated: .Agentica/competitor_intel.json, ROADMAP.md",
        "evolve": f"🧬 Auto-commit: Self-Evolution Swarm [{ts}]\n\nNL Swarm dispatched agents to bridge market gaps.\nUpdated: swarm manifest, report.json, ROADMAP.md",
        "audit": f"🔒 Auto-commit: Health Audit Complete [{ts}]\n\nVerify-all audit completed successfully.\nUpdated: audit logs",
    }.get(task, f"🦅 Auto-commit: Task '{task}' [{ts}]")

    result = git(["commit", "-m", msg])
    log(f"[*] Commit: {result[:80]}")

    push = git(["push", "origin", "main"])
    log(f"[+] Push result: {push}")


def main():
    task = sys.argv[1] if len(sys.argv) > 1 else "unknown"
    log(f"[*] Post-task hook running for: '{task}'")

    if task == "intel" and INTEL_PATH.exists():
        try:
            intel = json.loads(INTEL_PATH.read_text(encoding="utf-8"))
            update_roadmap_intel(intel)
        except Exception as e:
            log(f"[!] Could not update ROADMAP: {e}")

    commit_and_push(task)
    log("[+] Post-task hook complete.")


if __name__ == "__main__":
    main()
